version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install --silent
      - run: npm run build
  test:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install --silent
      - run: npm test
  helloworld:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
    - checkout
    - run: echo "Hello world!"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - helloworld
      - test:
          requires:
            - helloworld